apiVersion: v1
kind: Service
metadata:
  name: reorg-monitor
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app.kubernetes.io/name: reorg-monitor
    app.kubernetes.io/component: monitor
    app.kubernetes.io/part-of: reorg-monitor
  ports:
    - name: webserver
      port: 9090
      targetPort: webserver