apiVersion: apps/v1
kind: Deployment
metadata:
  name: reorg-monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: reorg-monitor
  template:
    metadata:
      labels:
        app.kubernetes.io/name: reorg-monitor
    spec:
      containers:
        - name: reorg-monitor
          image: flashbots/reorg-monitor:latest
          envFrom:
            - secretRef:
                name: reorg-monitor-secrets
          ports:
            - name: webserver
              containerPort: 9090