version: '3.1'

volumes:
  psql_data:
    driver: local

services:
  db:
    image: postgres
    restart: always
    volumes:
      - 'psql_data:/var/lib/postgresql/data'
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user1
      POSTGRES_PASSWORD: password
      POSTGRES_DB: reorg

  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 8092:8080
