on: [push, pull_request]
name: Checks
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install staticcheck
      run: go install honnef.co/go/tools/cmd/staticcheck

    - name: Lint
      run: |
        export PATH=$PATH:$(go env GOPATH)/bin
        make lint
      shell: bash

    - name: Test
      run: make test
